/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package window;

import javax.swing.table.DefaultTableModel;
import database.db_connection;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author MyBook Hype AMD
 */
public class adminMenu extends javax.swing.JInternalFrame {

    /**
     * Creates new form karyawanMenu
     */
    public adminMenu() {
        initComponents();
        view_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        karyawanTables = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nphoneField = new javax.swing.JTextField();

        setClosable(true);
        setResizable(true);
        setTitle("Admin Menu");

        karyawanTables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.", "ID", "Name", "Email", "N. Phone"
            }
        ));
        karyawanTables.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                karyawanTablesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(karyawanTables);

        jLabel1.setText("name:");

        jLabel2.setText("email:");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("ID: ");

        idField.setEditable(false);
        idField.setText("ID");

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("n. phone:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addGap(18, 18, 18)
                        .addComponent(editButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton))
                    .addComponent(resetButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel3))
                            .addGap(44, 44, 44)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nphoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(emailField))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(214, 214, 214))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nphoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(editButton)
                    .addComponent(deleteButton))
                .addGap(18, 18, 18)
                .addComponent(resetButton)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String nama = nameField.getText();
        String usia = emailField.getText();
        
        if(nama.equals("") || usia.equals("")) {
            JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong");
        } else {
            try {
                int usiaInt = Integer.parseInt(usia);
                String query = "INSERT INTO karyawan_tables (nama, usia) VALUES ('"+ nama +"', '"+ usiaInt +"')";
                Connection conn = (Connection)db_connection.configuration_db();
                PreparedStatement s = conn.prepareStatement(query);
                s.execute();
                JOptionPane.showMessageDialog(null, "Tambah Data Berhasil");
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, "Tambah Data Gagal");
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            view_table();
            clear_field();
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void karyawanTablesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_karyawanTablesMouseClicked
        // TODO add your handling code here:
        int row = karyawanTables.rowAtPoint(evt.getPoint());
        
        String id = karyawanTables.getValueAt(row, 1).toString();
        idField.setText(id);
        
        String nama = karyawanTables.getValueAt(row, 2).toString();
        nameField.setText(nama);
        
        String usia = karyawanTables.getValueAt(row, 3).toString();
        emailField.setText(usia);
    }//GEN-LAST:event_karyawanTablesMouseClicked

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        String id = idField.getText();
        String nama = nameField.getText();
        String usia = emailField.getText();
        
        if(id.equals("ID") || nama.equals("") || usia.equals("")) {
            JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong");
        } else {
            try {
                int usiaInt = Integer.parseInt(usia);
                String query = "UPDATE karyawan_tables SET nama = '"+ nama +"', usia = '"+ usiaInt +"' WHERE id = '"+ id +"'";
                Connection conn = (Connection)db_connection.configuration_db();
                PreparedStatement s = conn.prepareStatement(query);
                s.execute();
                JOptionPane.showMessageDialog(null, "Ubah Data Berhasil");
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, "Ubah Data Gagal");
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            view_table();
            clear_field();
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        String id = idField.getText();
        
        if(id.equals("ID")) {
            JOptionPane.showMessageDialog(null, "Pilih Datanya");
        } else {
            try {
                String query = "DELETE FROM karyawan_tables WHERE id = '"+ id +"'";
                Connection conn = (Connection)db_connection.configuration_db();
                PreparedStatement s = conn.prepareStatement(query);
                s.execute();
                JOptionPane.showMessageDialog(null, "Hapus Data Berhasil");
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, "Hapus Data Gagal");
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            view_table();
            clear_field();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        clear_field();
    }//GEN-LAST:event_resetButtonActionPerformed

    
    private void view_table() {
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("No.");
        tb.addColumn("ID");
        tb.addColumn("Nama");
        tb.addColumn("Usia");
        
        try {
            int counter = 1;
            String query = "SELECT * FROM karyawan_tables";
            Connection conn = (Connection)db_connection.configuration_db();
            Statement s = conn.createStatement();
            ResultSet r = s.executeQuery(query);
            while(r.next()) {
                tb.addRow(new Object[] {
                    counter++, r.getString(1), r.getString(2), r.getString(3)
                });
            }
            karyawanTables.setModel(tb);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }
    
    private void clear_field() {
        idField.setText("ID");
        nameField.setText("");
        emailField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable karyawanTables;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField nphoneField;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables
}
