/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package window;

import javax.swing.table.DefaultTableModel;
import database.db_connection;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author MyBook Hype AMD
 */
public class studioMenu extends javax.swing.JInternalFrame {

    /**
     * Creates new form karyawanMenu
     */
    public studioMenu() {
        initComponents();
        view_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        studioTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        priceField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        locationTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        descTextArea = new javax.swing.JTextArea();
        statusComboBox = new javax.swing.JComboBox<>();

        setClosable(true);
        setResizable(true);
        setTitle("Studio Menu");

        studioTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No.", "ID", "Name", "Price / Hr", "Desc", "Location", "Status"
            }
        ));
        studioTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studioTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(studioTable);

        jLabel1.setText("name:");

        jLabel2.setText("price / hr:");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("ID: ");

        idField.setEditable(false);
        idField.setText("ID");

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("desc:");

        jLabel5.setText("location:");

        jLabel6.setText("status:");

        locationTextArea.setColumns(20);
        locationTextArea.setRows(5);
        jScrollPane2.setViewportView(locationTextArea);

        descTextArea.setColumns(20);
        descTextArea.setRows(5);
        jScrollPane3.setViewportView(descTextArea);

        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idField, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(nameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(priceField)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(statusComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addButton)
                                .addGap(18, 18, 18)
                                .addComponent(editButton)
                                .addGap(18, 18, 18)
                                .addComponent(deleteButton))
                            .addComponent(resetButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(editButton)
                    .addComponent(deleteButton))
                .addGap(18, 18, 18)
                .addComponent(resetButton)
                .addGap(34, 34, 34))
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String name = nameField.getText();
        String price = priceField.getText();
        String desc = descTextArea.getText();
        String location = locationTextArea.getText();
        String status = statusComboBox.getSelectedItem().toString();
        
        if(name.equals("") || price.equals("")) {
            JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong");
        } else {
            try {
                int priceInt = Integer.parseInt(price);
                int statusInt;
                if(status.equals("Active")) {
                    statusInt = 1;
                } else {
                    statusInt = 0;
                }
                String query = "INSERT INTO studios (name, price_per_hour, description, location, is_available) VALUES ('"+ name +"', '"+ priceInt +"', '"+ desc +"', '"+ location +"', '"+ statusInt +"')";
                Connection conn = (Connection)db_connection.configuration_db();
                PreparedStatement s = conn.prepareStatement(query);
                s.execute();
                JOptionPane.showMessageDialog(null, "Tambah Data Berhasil");
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, "Tambah Data Gagal");
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            view_table();
            clear_field();
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void studioTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studioTableMouseClicked
        // TODO add your handling code here:
        int row = studioTable.rowAtPoint(evt.getPoint());
        
        String id = studioTable.getValueAt(row, 1).toString();
        idField.setText(id);
        
        String name = studioTable.getValueAt(row, 2).toString();
        nameField.setText(name);
        
        String price = studioTable.getValueAt(row, 3).toString();
        price = price.replace(".00", "");
        priceField.setText(price);
        
        String desc = studioTable.getValueAt(row, 4).toString();
        descTextArea.setText(desc);
        
        String location = studioTable.getValueAt(row, 5).toString();
        locationTextArea.setText(location);
        
        String status = studioTable.getValueAt(row, 6).toString();
        statusComboBox.setSelectedItem(status);
    }//GEN-LAST:event_studioTableMouseClicked

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        String id = idField.getText();
        String name = nameField.getText();
        String price = priceField.getText();
        String desc = descTextArea.getText();
        String location = locationTextArea.getText();
        String status = statusComboBox.getSelectedItem().toString();
        
        if(name.equals("") || price.equals("")) {
            JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong");
        } else {
            try {
                int priceInt = Integer.parseInt(price);
                int statusInt;
                if(status.equals("Active")) {
                    statusInt = 1;
                } else {
                    statusInt = 0;
                }
                String query = "UPDATE studios SET name = '"+ name +"', price_per_hour = '"+ priceInt +"', description = '"+ desc +"', location = '"+ location +"', is_available = '"+ statusInt +"' WHERE id = '"+ id +"'";
                Connection conn = (Connection)db_connection.configuration_db();
                PreparedStatement s = conn.prepareStatement(query);
                s.execute();
                JOptionPane.showMessageDialog(null, "Ubah Data Berhasil");
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, "Ubah Data Gagal");
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            view_table();
            clear_field();
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        String id = idField.getText();
        
        if(id.equals("ID")) {
            JOptionPane.showMessageDialog(null, "Pilih Datanya");
        } else {
            try {
                String query = "DELETE FROM studios WHERE id = '"+ id +"'";
                Connection conn = (Connection)db_connection.configuration_db();
                PreparedStatement s = conn.prepareStatement(query);
                s.execute();
                JOptionPane.showMessageDialog(null, "Hapus Data Berhasil");
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, "Hapus Data Gagal");
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            view_table();
            clear_field();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        clear_field();
    }//GEN-LAST:event_resetButtonActionPerformed

    
    private void view_table() {
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("No.");
        tb.addColumn("ID");
        tb.addColumn("Name");
        tb.addColumn("Price / Hr");
        tb.addColumn("Desc");
        tb.addColumn("Location");
        tb.addColumn("Status");
        
        try {
            int counter = 1;
            String query = "SELECT * FROM studios";
            Connection conn = (Connection)db_connection.configuration_db();
            Statement s = conn.createStatement();
            ResultSet r = s.executeQuery(query);
            while(r.next()) {
                String studioStatus;
                if(r.getString(6).equals("1")) {
                    studioStatus = "Active";
                } else {
                    studioStatus = "Inactive";
                }
                tb.addRow(new Object[] {
                    counter++, r.getString(1), r.getString(2), r.getString(5), r.getString(4), r.getString(3), studioStatus
                });
            }
            studioTable.setModel(tb);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }
    
    private void clear_field() {
        idField.setText("ID");
        nameField.setText("");
        priceField.setText("");
        locationTextArea.setText("");
        descTextArea.setText("");
        statusComboBox.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextArea descTextArea;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea locationTextArea;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField priceField;
    private javax.swing.JButton resetButton;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JTable studioTable;
    // End of variables declaration//GEN-END:variables
}
